
name: 部署文档

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - master

jobs:
  deploy-fitsadmin-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: 安装依赖
        run: npm install

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |-
          npm run docs:github
          > docs/.vuepress/dist/.nojekyll

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          repository-name: caoguanjie/fitsadmin
          # 令牌，是要你的GitHub设置了这个ACCESS_TOKEN属性的令牌，代替你的账号密码
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          branch: docs
          # folder这个关键字，主要是把你写这个路径的文件直接提交到分支
          folder: docs/.vuepress/dist

