name: Create Release

on:
    push:
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10 

permissions: {}
jobs:
    build:
      permissions:
        contents: write 
  
      name: Create Release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@master
        - name: Create Release for Tag
          id: release_tag
          uses: yyx990803/release-tag@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            body: |
              详情信息请参阅 [CHANGELOG.md](https://github.com/caoguanjie/fitsadmin/blob/master/main/CHANGELOG.md) 
        
  