name: Create Release

on:
    push:
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10 

permissions: {}
jobs:
    build:
      permissions:
        contents: write 
  
      name: Create Release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@master
        - name: Create Release for Tag
          id: release_tag
          uses: release-drafter/release-drafter@v5
          env:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            body: |
              Please refer to [CHANGELOG.md](https://github.com/vuejs/core/blob/main/CHANGELOG.md) for details.
        
  